version: '3.8'

services:
  nuxt-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9002:9002" # Map port 9002 of the container to port 9002 on the host
    environment:
      PORT: 9002
    volumes:
      - .:/app # Optional: Mount local directory for live updates (not recommended for production)
      - /app/node_modules # Prevent overwriting node_modules by the volume
