version: '3.8'

services:
  nuxt-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Map port 3000 of the container to port 3000 on the host
    networks:
      - web
    # environment:
    #   PORT: 3000
    volumes:
      - .:/app # Optional: Mount local directory for live updates (not recommended for production)
      - /app/node_modules # Prevent overwriting node_modules by the volume
  nginx:
    image: nginx
    container_name: nginx-container
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80" # Map container's port 80 to host's port 8080
    networks:
      - web

networks:
  web:
    driver: bridge