
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'Home': typeof import("../components/Home.vue")['default']
    'LoadingScreen': typeof import("../components/LoadingScreen.vue")['default']
    'Login': typeof import("../components/Login.vue")['default']
    'Pagination': typeof import("../components/Pagination.vue")['default']
    'Register': typeof import("../components/Register.vue")['default']
    'DashboardContainer': typeof import("../components/dashboard/Container.vue")['default']
    'DashboardSetupHomepage': typeof import("../components/dashboard/SetupHomepage.vue")['default']
    'DashboardSidebar': typeof import("../components/dashboard/Sidebar.vue")['default']
    'DashboardUserRead': typeof import("../components/dashboard/UserRead.vue")['default']
    'DashboardUserUnread': typeof import("../components/dashboard/UserUnread.vue")['default']
    'LayoutsFooter': typeof import("../components/layouts/Footer.vue")['default']
    'LayoutsHeader': typeof import("../components/layouts/Header.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
    'NuxtPicture': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
    'MyPrefixCarousel': typeof import("vue3-carousel/dist/carousel")['Carousel']
    'MyPrefixSlide': typeof import("vue3-carousel/dist/carousel")['Slide']
    'MyPrefixPagination': typeof import("vue3-carousel/dist/carousel")['Pagination']
    'MyPrefixNavigation': typeof import("vue3-carousel/dist/carousel")['Navigation']
    'Field': typeof import("vee-validate")['Field']
    'Form': typeof import("vee-validate")['Form']
    'ErrorMessage': typeof import("vee-validate")['ErrorMessage']
    'FieldArray': typeof import("vee-validate")['FieldArray']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyHome': typeof import("../components/Home.vue")['default']
    'LazyLoadingScreen': typeof import("../components/LoadingScreen.vue")['default']
    'LazyLogin': typeof import("../components/Login.vue")['default']
    'LazyPagination': typeof import("../components/Pagination.vue")['default']
    'LazyRegister': typeof import("../components/Register.vue")['default']
    'LazyDashboardContainer': typeof import("../components/dashboard/Container.vue")['default']
    'LazyDashboardSetupHomepage': typeof import("../components/dashboard/SetupHomepage.vue")['default']
    'LazyDashboardSidebar': typeof import("../components/dashboard/Sidebar.vue")['default']
    'LazyDashboardUserRead': typeof import("../components/dashboard/UserRead.vue")['default']
    'LazyDashboardUserUnread': typeof import("../components/dashboard/UserUnread.vue")['default']
    'LazyLayoutsFooter': typeof import("../components/layouts/Footer.vue")['default']
    'LazyLayoutsHeader': typeof import("../components/layouts/Header.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
    'LazyNuxtPicture': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
    'LazyMyPrefixCarousel': typeof import("vue3-carousel/dist/carousel")['Carousel']
    'LazyMyPrefixSlide': typeof import("vue3-carousel/dist/carousel")['Slide']
    'LazyMyPrefixPagination': typeof import("vue3-carousel/dist/carousel")['Pagination']
    'LazyMyPrefixNavigation': typeof import("vue3-carousel/dist/carousel")['Navigation']
    'LazyField': typeof import("vee-validate")['Field']
    'LazyForm': typeof import("vee-validate")['Form']
    'LazyErrorMessage': typeof import("vee-validate")['ErrorMessage']
    'LazyFieldArray': typeof import("vee-validate")['FieldArray']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const Home: typeof import("../components/Home.vue")['default']
export const LoadingScreen: typeof import("../components/LoadingScreen.vue")['default']
export const Login: typeof import("../components/Login.vue")['default']
export const Pagination: typeof import("../components/Pagination.vue")['default']
export const Register: typeof import("../components/Register.vue")['default']
export const DashboardContainer: typeof import("../components/dashboard/Container.vue")['default']
export const DashboardSetupHomepage: typeof import("../components/dashboard/SetupHomepage.vue")['default']
export const DashboardSidebar: typeof import("../components/dashboard/Sidebar.vue")['default']
export const DashboardUserRead: typeof import("../components/dashboard/UserRead.vue")['default']
export const DashboardUserUnread: typeof import("../components/dashboard/UserUnread.vue")['default']
export const LayoutsFooter: typeof import("../components/layouts/Footer.vue")['default']
export const LayoutsHeader: typeof import("../components/layouts/Header.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
export const NuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
export const MyPrefixCarousel: typeof import("vue3-carousel/dist/carousel")['Carousel']
export const MyPrefixSlide: typeof import("vue3-carousel/dist/carousel")['Slide']
export const MyPrefixPagination: typeof import("vue3-carousel/dist/carousel")['Pagination']
export const MyPrefixNavigation: typeof import("vue3-carousel/dist/carousel")['Navigation']
export const Field: typeof import("vee-validate")['Field']
export const Form: typeof import("vee-validate")['Form']
export const ErrorMessage: typeof import("vee-validate")['ErrorMessage']
export const FieldArray: typeof import("vee-validate")['FieldArray']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyHome: typeof import("../components/Home.vue")['default']
export const LazyLoadingScreen: typeof import("../components/LoadingScreen.vue")['default']
export const LazyLogin: typeof import("../components/Login.vue")['default']
export const LazyPagination: typeof import("../components/Pagination.vue")['default']
export const LazyRegister: typeof import("../components/Register.vue")['default']
export const LazyDashboardContainer: typeof import("../components/dashboard/Container.vue")['default']
export const LazyDashboardSetupHomepage: typeof import("../components/dashboard/SetupHomepage.vue")['default']
export const LazyDashboardSidebar: typeof import("../components/dashboard/Sidebar.vue")['default']
export const LazyDashboardUserRead: typeof import("../components/dashboard/UserRead.vue")['default']
export const LazyDashboardUserUnread: typeof import("../components/dashboard/UserUnread.vue")['default']
export const LazyLayoutsFooter: typeof import("../components/layouts/Footer.vue")['default']
export const LazyLayoutsHeader: typeof import("../components/layouts/Header.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
export const LazyNuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
export const LazyMyPrefixCarousel: typeof import("vue3-carousel/dist/carousel")['Carousel']
export const LazyMyPrefixSlide: typeof import("vue3-carousel/dist/carousel")['Slide']
export const LazyMyPrefixPagination: typeof import("vue3-carousel/dist/carousel")['Pagination']
export const LazyMyPrefixNavigation: typeof import("vue3-carousel/dist/carousel")['Navigation']
export const LazyField: typeof import("vee-validate")['Field']
export const LazyForm: typeof import("vee-validate")['Form']
export const LazyErrorMessage: typeof import("vee-validate")['ErrorMessage']
export const LazyFieldArray: typeof import("vee-validate")['FieldArray']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
